version: '3'

services:
  dobble-generator:
    build: .
    container_name: dobble-generator
    restart: unless-stopped
    ports:
      - "8920:8920"
    volumes:
      - dobble_uploads:/app/uploads
      - dobble_logs:/app/logs
    environment:
      - TZ=Europe/London
    labels:
      - "com.unraid.docker.icon=https://cdn-icons-png.flaticon.com/512/4696/4696624.png"
      - "com.unraid.docker.webui=http://[IP]:[PORT:8920]/"
      - "com.unraid.docker.overview=Dobble Card Generator - Create your own Dobble/Spot It cards with custom images or icons."
      - "com.unraid.docker.template_url=https://github.com/istinmth/dobble-generator/templates/docker-template.xml"

volumes:
  dobble_uploads:
    driver: local
  dobble_logs:
    driver: local